### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/Conference_Workshops_2019#6]
The link urls don't work for all but one of the hyperlinks.

**Comment by Gautam-Arora24** [comment]
Kindly explain more about the issue, so that I can get to know what's the actual problem

**Comment by Lextuga007** [comment]
I moved the files from subfolders into the main folder and then copied over the READMEs to one in the main file but I just copied all the URLs to the presentations and changed the file names. Because it was on a branch called develop I couldn't check them but it looks like the whole URL path needs altering.

**Comment by poleselfg** [comment]
i can help!

**Comment by ChrisBeeley** [comment]
Closed by #7 , sorry it took so long and thanks!
